// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Map from "rescript/lib/es6/belt_Map.js";
import * as Belt_List from "rescript/lib/es6/belt_List.js";

function add(todoMap, text) {
  var match = Belt_List.head(Belt_List.reverse(Belt_Map.toList(todoMap)));
  var id = match !== undefined ? match[0] + 1 | 0 : 1;
  var todo = {
    id: id,
    text: text,
    status: /* ToDo */0
  };
  return Belt_Map.set(todoMap, id, todo);
}

var remove = Belt_Map.remove;

var update = Belt_Map.set;

export {
  add ,
  remove ,
  update ,
}
/* No side effect */
