// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function add(todoArr, text) {
  var last = Belt_List.head(Belt_List.reverse(Belt_List.fromArray(todoArr)));
  var id = last !== undefined ? last.id + 1 | 0 : 1;
  return Belt_Array.concat(todoArr, [{
                id: id,
                text: text,
                status: /* Todo */0
              }]);
}

function remove(todoArr, id) {
  return Belt_Array.keep(todoArr, (function (todo) {
                return todo.id !== id;
              }));
}

function update(todoArr, todo) {
  return Belt_Array.map(todoArr, (function (t) {
                if (t.id === todo.id) {
                  return todo;
                } else {
                  return t;
                }
              }));
}

export {
  add ,
  remove ,
  update ,
}
/* No side effect */
