// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import Rodal from "rodal";
import * as Filter from "../util/Filter.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function EditTodo(Props) {
  var defaultValue = Props.defaultValue;
  var visible = Props.visible;
  var close = Props.close;
  var save = Props.save;
  var match = React.useState(function () {
        return defaultValue;
      });
  var setValue = match[1];
  var value = match[0];
  var onChange = function (e) {
    var v = e.currentTarget.value;
    Curry._1(setValue, (function (param) {
            return v;
          }));
  };
  var submit = function (e) {
    e.preventDefault();
    Belt_Option.map(Filter.emptyStr(value), save);
    Curry._1(close, undefined);
  };
  return React.createElement(Rodal, {
              visible: visible,
              onClose: close,
              children: React.createElement("div", {
                    className: "modal-content"
                  }, React.createElement("form", {
                        onSubmit: submit
                      }, React.createElement("input", {
                            className: "modal-input",
                            value: value,
                            onChange: onChange
                          }), React.createElement("div", {
                            className: "modal-buttons-container"
                          }, React.createElement("button", {
                                className: "modal-button",
                                onClick: (function (param) {
                                    Curry._1(close, undefined);
                                  })
                              }, "취소"), React.createElement("button", {
                                className: "modal-button",
                                type: "submit"
                              }, "저장"))))
            });
}

var make = EditTodo;

export {
  make ,
}
/* react Not a pure module */
