// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Filter from "../util/Filter.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function TodoInput(Props) {
  var addTodo = Props.addTodo;
  var match = React.useState(function () {
        return "";
      });
  var setValue = match[1];
  var value = match[0];
  var onChange = function (e) {
    var v = e.currentTarget.value;
    Curry._1(setValue, (function (param) {
            return v;
          }));
  };
  var submit = function (e) {
    e.preventDefault();
    Belt_Option.map(Filter.emptyStr(value), addTodo);
    Curry._1(setValue, (function (param) {
            return "";
          }));
  };
  return React.createElement("form", {
              onSubmit: submit
            }, React.createElement("div", {
                  className: "todo-input-container"
                }, React.createElement("input", {
                      value: value,
                      onChange: onChange
                    }), React.createElement("button", {
                      type: "submit"
                    }, "추가")));
}

var make = TodoInput;

export {
  make ,
}
/* react Not a pure module */
