// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function TodoListItem(Props) {
  var todo = Props.todo;
  var removeTodo = Props.removeTodo;
  var toggleStatus = Props.toggleStatus;
  var text = todo.text;
  var onClickRemove = function (param) {
    Curry._1(removeTodo, todo);
  };
  var onClickTodo = function (param) {
    Curry._1(toggleStatus, todo);
  };
  return React.createElement("li", {
              className: "todoItem"
            }, React.createElement("div", {
                  onClick: onClickTodo
                }, React.createElement("span", undefined, String(todo.id)), todo.status ? React.createElement("div", {
                        className: "done"
                      }, text) : React.createElement("div", undefined, text)), React.createElement("button", {
                  onClick: onClickRemove
                }, "삭제"));
}

var make = TodoListItem;

export {
  make ,
}
/* react Not a pure module */
