// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function getValue(e) {
  return e.currentTarget.value;
}

function TodoInput(Props) {
  var addTodo = Props.addTodo;
  var match = React.useState(function () {
        return "";
      });
  var setTodo = match[1];
  var todo = match[0];
  var onChange = function ($$event) {
    var value = $$event.currentTarget.value;
    setTodo(function (param) {
          return value;
        });
  };
  var onClickAdd = function (param) {
    if (todo !== "") {
      Curry._1(addTodo, todo);
      return setTodo(function (param) {
                  return "";
                });
    }
    
  };
  return React.createElement("div", {
              className: "todoForm"
            }, React.createElement("input", {
                  value: todo,
                  onChange: onChange
                }), React.createElement("button", {
                  onClick: onClickAdd
                }, "추가"));
}

var make = TodoInput;

export {
  getValue ,
  make ,
}
/* react Not a pure module */
