// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function TodoListItem(Props) {
  var todo = Props.todo;
  return React.createElement("li", {
              className: "todo-list-item-container"
            }, React.createElement("div", {
                  className: "todo-list-item-content"
                }, React.createElement("div", undefined, todo)));
}

var make = TodoListItem;

export {
  make ,
}
/* react Not a pure module */
