// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml from "rescript/lib/es6/caml.js";
import * as Belt_Id from "rescript/lib/es6/belt_Id.js";
import * as Belt_Set from "rescript/lib/es6/belt_Set.js";
import * as Belt_List from "rescript/lib/es6/belt_List.js";

function cmp(todoA, todoB) {
  return Caml.int_compare(todoA.id, todoB.id);
}

var IdComparator = Belt_Id.MakeComparable({
      cmp: cmp
    });

var todoSet = Belt_Set.fromArray([], IdComparator);

function addTodo(prev, text) {
  var last = Belt_List.head(Belt_List.reverse(Belt_Set.toList(prev)));
  var id = last !== undefined ? last.id + 1 | 0 : 1;
  return Belt_Set.add(prev, {
              id: id,
              text: text,
              status: /* ToDo */0
            });
}

var removeTodo = Belt_Set.remove;

function toggleStatus(prev, todo) {
  var match = todo.status;
  return Belt_Set.add(Belt_Set.remove(prev, todo), {
              id: todo.id,
              text: todo.text,
              status: match ? /* ToDo */0 : /* Done */1
            });
}

export {
  IdComparator ,
  todoSet ,
  addTodo ,
  removeTodo ,
  toggleStatus ,
}
/* IdComparator Not a pure module */
