// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Auth from "../entities/Auth.mjs";
import * as React from "react";

function User(Props) {
  var user = Auth.useUser(undefined);
  if (user !== undefined) {
    return React.createElement("div", {
                className: "mb-2 flex gap-4"
              }, React.createElement("div", {
                    className: "text-white flex items-center text-end"
                  }, React.createElement("div", undefined, "" + user.firstName + " " + user.lastName + "", React.createElement("div", {
                            className: "text-xs"
                          }, "@" + user.userName + ""))), React.createElement("img", {
                    className: "h-12 w-12 rounded-full ring-2",
                    alt: "avatar",
                    src: user.avatar
                  }));
  } else {
    return null;
  }
}

var make = User;

export {
  make ,
}
/* Auth Not a pure module */
